### ISSUE TITLE
Delete Stack if Already Exists fails

### ISSUE THREAD

**Issue by frizop** [CreditMutuelArkea/Openstack-Jenkins-HeatPlugin#2]
Building in workspace /var/lib/jenkins/jobs/Build Heat - Example Puppet/workspace
    HOT PlayerINFO : Stack existing : puppet-demo
    HOT PlayerINFO : Delete in progress...
    FATAL: org.openstack4j.api.heat.StackService.delete(Ljava/lang/String;Ljava/lang/String;)Lorg/openstack4j/model/common/ActionResponse;
    java.lang.NoSuchMethodError: org.openstack4j.api.heat.StackService.delete(Ljava/lang/String;Ljava/lang/String;)Lorg/openstack4j/model/common/ActionResponse;
      at com.arkea.jenkins.openstack.client.OpenStack4jClient.deleteStack(OpenStack4jClient.java:135)
      at com.arkea.jenkins.openstack.operations.StackOperationsUtils.deleteStack(StackOperationsUtils.java:74)
      at com.arkea.jenkins.openstack.heat.HOTPlayer.perform(HOTPlayer.java:142)
      at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
      at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
      at hudson.model.Build$BuildExecution.build(Build.java:205)
      at hudson.model.Build$BuildExecution.doRun(Build.java:162)
      at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
      at hudson.model.Run.execute(Run.java:1728)
      at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
      at hudson.model.ResourceController.execute(ResourceController.java:98)
      at hudson.model.Executor.run(Executor.java:404)
    Finished: FAILURE

**Comment by CMArkea** [comment]
@frizop, thanks to report, could you please open the issue on the official jenkinsci plugin github repo : https://github.com/jenkinsci/openstack-heat-plugin
